import { type NextPage } from "next"
import Head from "next/head"
import {useEffect, useState, useRef} from 'react'

import {Wrapper} from '@googlemaps/react-wrapper'

import {env} from '@/env/client.mjs'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-white flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Wrapper apiKey={env.NEXT_PUBLIC_MAPS_KEY} render={() => <h1>Test</h1>}>
          <Map/>
        </Wrapper>
      </main>
    </>
  )
}

export default Home


const Map = () => {
  const ref = useRef<HTMLDivElement>(null)
  const [map, setMap] = useState<google.maps.Map>()

  useEffect(() => {
    if (ref.current && !map) {
      setMap(new window.google.maps.Map(ref.current, {
        fullscreenControl: false,
        streetViewControl: false,
        mapTypeControl: false,
        center: {lat: 51, lng: 10},
        zoom: 7,
        styles: [
          {
            featureType: 'poi',
            stylers: [
              {visibility: 'off'}
            ]
          }
        ]
      }))
    }
  }, [ref, map])

  useEffect(() => {
    if (!map)
      return

    navigator.geolocation.getCurrentPosition(({coords}) => {
      map.setCenter({
        lat: coords.latitude,
        lng: coords.longitude
      })
      map.setZoom(12)
    })

    map.addListener('click', ({latLng}: {latLng: {lat: () => number, lng: () => number}}) => {
      const lat = latLng.lat()
      const lng = latLng.lng()

      const marker = new window.google.maps.Marker({map, position: {lat, lng}, animation: google.maps.Animation.DROP, label: 'Hello World'})
    })
  }, [map])

  return <>
    <div ref={ref} className="w-screen h-screen"/>
  </>
}